# Generated by Django 3.2.9 on 2022-04-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(default='', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RI', 'Researcher'), ('PR', 'Senior Researcher'), ('DR', 'Research Director')], default='RI', max_length=2)),
                ('start_date', models.DateField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.researcher')),
            ],
            options={
                'ordering': ['researcher', 'start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='researcher',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='projects_researcher_unique'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name',), name='projects_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='workpackage',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='projects_workpackage_unique'),
        ),
        migrations.AddConstraint(
            model_name='researcherrole',
            constraint=models.UniqueConstraint(fields=('researcher', 'start_date'), name='projects_researcherrole_unique'),
        ),
    ]
