# Generated by Django 3.2.5 on 2022-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_copy_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
