# Generated by Django 3.2.5 on 2022-04-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20220411_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Projects.researcher'),
        ),
        migrations.AlterField(
            model_name='researcherrole',
            name='role',
            field=models.CharField(choices=[('RI', 'Researcher'), ('PR', 'Senior Researcher'), ('DR', 'Research Director'), ('ID', 'Institute Director'), ('FP', 'Full Professor'), ('AP', 'Associate Professor')], default='RI', max_length=2),
        ),
    ]
