# Generated by Django 3.2.5 on 2022-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_researcher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherrole',
            name='role',
            field=models.CharField(choices=[('TD', 'Researcher (TD)'), ('RI', 'Researcher'), ('PR', 'Senior Researcher'), ('DR', 'Research Director'), ('ID', 'Institute Director'), ('FP', 'Full Professor'), ('AP', 'Associate Professor')], default='RI', max_length=2),
        ),
    ]
