# Generated by Django 3.2.5 on 2022-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_researcherrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sigla_cup',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sigla_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sigla_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
