# Generated by Django 3.2.5 on 2022-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20220422_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sigla_cup',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sigla_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sigla_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
