# Generated by Django 4.0.4 on 2022-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_project_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agency',
            field=models.CharField(choices=[('EU-H2020', 'EU-H2020'), ('EU-HorizonEu', 'EU-HorizonEu'), ('MUR', 'MUR'), ('CNR', 'CNR')], max_length=200),
        ),
    ]
