# Generated by Django 4.0.4 on 2022-08-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_alter_project_options_alter_researcher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('project_view', 'View list of projects'), ('project_manage', 'Manage list of projects')]},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'default_permissions': (), 'ordering': ['surname', 'name'], 'permissions': [('researcher_view', 'View list of researchers'), ('researcher_manage', 'Manage list of researchers')]},
        ),
        migrations.AlterModelOptions(
            name='researcherrole',
            options={'default_permissions': (), 'ordering': ['researcher', 'start_date'], 'permissions': [('role_manage_own', 'Modify own role')]},
        ),
    ]
