# Generated by Django 3.2.9 on 2023-01-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_alter_project_options_alter_researcher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_for_conflict', to='Projects.researcher')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_in_conflict', to='Projects.researcher')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='Projects.researcher')),
            ],
            options={
                'verbose_name_plural': 'ConflictsOfInterest',
                'ordering': ['director', 'researcher', '-start_date'],
                'permissions': [('conflict_manage', 'Manage conflicts of interest')],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='conflictofinterest',
            constraint=models.UniqueConstraint(fields=('researcher', 'director', 'start_date'), name='projects_conflictofinterest_unique'),
        ),
    ]
