# Generated by Django 3.2.9 on 2023-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0014_auto_20230118_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictofinterest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
