# Generated by Django 3.2.5 on 2021-07-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('RI', 'Researcher'), ('PR', 'Senior Researcher'), ('DR', 'Research Director')], default='RI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetMods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours_diff', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.project')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('hours', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.project')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='PersonellCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('working_hours', models.PositiveIntegerField()),
                ('cost', models.FloatField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('reason', models.CharField(choices=[('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness')], default='HO', max_length=2)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher')),
            ],
        ),
    ]
