# Generated by Django 3.2.5 on 2022-03-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='EpasCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('ts_code', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('working_hours', models.PositiveIntegerField()),
                ('cost', models.FloatField()),
            ],
            options={
                'ordering': ['year', 'researcher'],
            },
        ),
        migrations.CreateModel(
            name='PresenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('ts_hours', models.FloatField()),
                ('ts_code', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2)),
            ],
            options={
                'ordering': ['researcher', 'day'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_start', models.DateField()),
                ('rp_end', models.DateField()),
                ('hours', models.FloatField()),
                ('has_missions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('RI', 'Researcher'), ('PR', 'Senior Researcher'), ('DR', 'Research Director')], default='RI', max_length=2)),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(default='', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetMissionHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.presencedata')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.reporting')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.reporting')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hours', models.FloatField()),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.reporting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='researcher',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='financialreporting_researcher_unique'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FinancialReporting.personnelcost'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.project'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='wp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.workpackage'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name',), name='financialreporting_project_unique'),
        ),
        migrations.AddField(
            model_name='presencedata',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FinancialReporting.epascode'),
        ),
        migrations.AddField(
            model_name='presencedata',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher'),
        ),
        migrations.AddField(
            model_name='personnelcost',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher'),
        ),
        migrations.AddConstraint(
            model_name='epascode',
            constraint=models.UniqueConstraint(fields=('code',), name='financialreporting_epascode_unique'),
        ),
        migrations.AddConstraint(
            model_name='bankholiday',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'day'), name='financialreporting_bankholiday_unique'),
        ),
        migrations.AddConstraint(
            model_name='workpackage',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='financialreporting_workpackage_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheetmissionhint',
            constraint=models.UniqueConstraint(fields=('missionday',), name='financialreporting_timesheetmissionhint_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheethours',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'day'), name='financialreporting_timesheethours_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheethint',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'year', 'month'), name='financialreporting_timesheethint_unique'),
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.UniqueConstraint(fields=('researcher', 'project', 'wp', 'rp_start', 'rp_end'), name='financialreporting_reporting_unique'),
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.CheckConstraint(check=models.Q(('rp_start__lt', django.db.models.expressions.F('rp_end'))), name='financialreporting_reporting_start_lt_end'),
        ),
        migrations.AddConstraint(
            model_name='presencedata',
            constraint=models.UniqueConstraint(fields=('researcher', 'day'), name='financialreporting_presencedata_unique'),
        ),
        migrations.AddConstraint(
            model_name='personnelcost',
            constraint=models.UniqueConstraint(fields=('year', 'researcher'), name='financialreporting_personnelcost_unique'),
        ),
    ]
