# Generated by Django 3.2.5 on 2021-07-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absences',
            new_name='Absence',
        ),
        migrations.RenameModel(
            old_name='PersonellCosts',
            new_name='PersonellCost',
        ),
        migrations.RenameModel(
            old_name='TimeSheetMods',
            new_name='TimeSheetMod',
        ),
    ]
