# Generated by Django 3.2.5 on 2022-03-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='role',
        ),
        migrations.CreateModel(
            name='ResearcherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RI', 'Researcher'), ('PR', 'Senior Researcher'), ('DR', 'Research Director')], default='RI', max_length=2)),
                ('start_date', models.DateField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher')),
            ],
            options={
                'ordering': ['researcher', 'start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='researcherrole',
            constraint=models.UniqueConstraint(fields=('researcher', 'start_date'), name='financialreporting_researcherrole_unique'),
        ),
    ]
