# Generated by Django 3.2.5 on 2021-07-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0003_bankholidays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankHolidays',
            new_name='BankHoliday',
        ),
    ]
