# Generated by Django 3.2.9 on 2022-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0003_auto_20220406_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelcost',
            options={'ordering': ['year', 'n_researcher']},
        ),
        migrations.AlterModelOptions(
            name='presencedata',
            options={'ordering': ['n_researcher', 'day']},
        ),
        migrations.RemoveConstraint(
            model_name='reporting',
            name='financialreporting_reporting_unique',
        ),
        migrations.RemoveField(
            model_name='personnelcost',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='presencedata',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='wp',
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.UniqueConstraint(fields=('n_researcher', 'n_project', 'n_wp', 'rp_start', 'rp_end'), name='financialreporting_reporting_unique'),
        ),
    ]
