# Generated by Django 3.2.5 on 2021-07-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0004_rename_bankholidays_bankholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankholiday',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
