# Generated by Django 3.2.9 on 2022-04-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_copy_data'),
        ('FinancialReporting', '0005_auto_20220406_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelcost',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.researcher'),
        ),
        migrations.AlterField(
            model_name='presencedata',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.researcher'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.researcher'),
        ),
    ]
