# Generated by Django 3.2.7 on 2021-11-23 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0005_alter_bankholiday_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('ts_hours', models.FloatField()),
                ('reason', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='timesheetmod',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timesheetmod',
            name='researcher',
        ),
        migrations.AlterModelOptions(
            name='bankholiday',
            options={'ordering': ['year', 'month', 'day']},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='year',
        ),
        migrations.AddField(
            model_name='reporting',
            name='rp_end',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 12, 19, 54, 386037, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporting',
            name='rp_start',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 12, 20, 2, 215047, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='TimeSheetMod',
        ),
        migrations.AddField(
            model_name='workpackage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.project'),
        ),
        migrations.AddField(
            model_name='presencedata',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.researcher'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='wp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.workpackage'),
            preserve_default=False,
        ),
    ]
