# Generated by Django 3.2.7 on 2021-11-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0006_auto_20211123_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personellcost',
            options={'ordering': ['year', 'researcher']},
        ),
        migrations.AlterModelOptions(
            name='presencedata',
            options={'ordering': ['researcher', 'day']},
        ),
        migrations.AddField(
            model_name='reporting',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporting',
            name='wp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.workpackage'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='personellcost',
            constraint=models.UniqueConstraint(fields=('year', 'researcher'), name='unique_cost'),
        ),
        migrations.AddConstraint(
            model_name='presencedata',
            constraint=models.UniqueConstraint(fields=('researcher', 'day'), name='unique_day'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_project'),
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.UniqueConstraint(fields=('researcher', 'project', 'rp_start', 'rp_end'), name='unique_report'),
        ),
        migrations.AddConstraint(
            model_name='researcher',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='unique_researcher'),
        ),
        migrations.AddConstraint(
            model_name='workpackage',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_wp'),
        ),
    ]
