# Generated by Django 3.2.9 on 2022-04-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0006_auto_20220406_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherrole',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='ResearcherRole',
        ),
        migrations.DeleteModel(
            name='WorkPackage',
        ),
    ]
