# Generated by Django 3.2.7 on 2021-11-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0007_auto_20211124_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonellCost',
            new_name='PersonnelCost',
        ),
        migrations.AlterField(
            model_name='reporting',
            name='wp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.workpackage'),
        ),
    ]
