# Generated by Django 3.2.5 on 2022-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0007_auto_20220406_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epascode',
            name='code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='personnelcost',
            name='year',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='presencedata',
            name='day',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='rp_end',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='rp_start',
            field=models.DateField(db_index=True),
        ),
    ]
