# Generated by Django 3.2.5 on 2022-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0008_auto_20220411_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='has_missions',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='timesheethint',
            name='month',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='timesheethint',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='timesheethours',
            name='day',
            field=models.DateField(db_index=True),
        ),
    ]
