# Generated by Django 3.2.9 on 2021-11-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0009_epascode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epascode',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='presencedata',
            name='reason',
        ),
        migrations.AddField(
            model_name='presencedata',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FinancialReporting.epascode'),
        ),
    ]
