# Generated by Django 4.0.4 on 2022-08-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0009_auto_20220413_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankholiday',
            options={'default_permissions': (), 'ordering': ['year', 'month', 'day']},
        ),
        migrations.AlterModelOptions(
            name='epascode',
            options={'default_permissions': (), 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='personnelcost',
            options={'default_permissions': (), 'ordering': ['year', 'researcher']},
        ),
        migrations.AlterModelOptions(
            name='presencedata',
            options={'default_permissions': (), 'ordering': ['researcher', 'day']},
        ),
        migrations.AlterModelOptions(
            name='reporting',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='timesheethint',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='timesheethours',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='timesheetmissionhint',
            options={'default_permissions': ()},
        ),
    ]
