# Generated by Django 3.2.7 on 2021-11-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0010_auto_20211127_2004'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reporting',
            name='unique_report',
        ),
        migrations.AddField(
            model_name='reporting',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FinancialReporting.personnelcost'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.UniqueConstraint(fields=('researcher', 'project', 'wp', 'rp_start', 'rp_end'), name='unique_report'),
        ),
    ]
