# Generated by Django 3.2.7 on 2021-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0011_auto_20211129_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workpackage',
            options={'ordering': ['project__name', 'name']},
        ),
        migrations.AddField(
            model_name='presencedata',
            name='ts_code',
            field=models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='epascode',
            name='ts_code',
            field=models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2),
        ),
    ]
