# Generated by Django 3.2.7 on 2021-12-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0012_auto_20211216_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetHints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hours', models.FloatField()),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.reporting')),
            ],
        ),
    ]
