# Generated by Django 3.2.7 on 2021-12-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0013_timesheethints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimesheetHints',
            new_name='TimesheetHint',
        ),
    ]
