# Generated by Django 3.2.9 on 2022-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0014_rename_timesheethints_timesheethint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timesheethint',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'year', 'month'), name='unique_hint'),
        ),
    ]
