# Generated by Django 3.2.9 on 2022-01-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0015_timesheethint_unique_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='has_missions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimesheetHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.reporting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timesheethours',
            constraint=models.UniqueConstraint(fields=('reporting_period', 'day'), name='unique_ts_hours'),
        ),
    ]
