# Generated by Django 3.2.7 on 2022-01-24 11:18

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0016_auto_20220123_1030'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reporting',
            name='unique_report',
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.UniqueConstraint(fields=('researcher', 'project', 'wp', 'rp_start', 'rp_end'), name='financialreporting_unique_report'),
        ),
        migrations.AddConstraint(
            model_name='reporting',
            constraint=models.CheckConstraint(check=models.Q(('rp_start__lt', django.db.models.expressions.F('rp_end'))), name='financialreporting_rp_start_lt_rp_end'),
        ),
    ]
