# Generated by Django 3.2.5 on 2022-01-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialReporting', '0018_auto_20220124_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetMissionHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.presencedata')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinancialReporting.reporting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timesheetmissionhint',
            constraint=models.UniqueConstraint(fields=('missionday',), name='financialreporting_timesheetmissionhint_unique'),
        ),
    ]
