# Generated by Django 4.2.20 on 2025-04-14 13:41

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# Reporting.migrations.0003_auto_20220707_1939
# Reporting.migrations.0005_auto_20220718_1112
# NOTE: RunPython blocks refer to data migrations of old installation. Not needed in a new installation.

class Migration(migrations.Migration):

    replaces = [('Reporting', '0001_initial'), ('Reporting', '0002_reportedmission_workpackage'), ('Reporting', '0003_auto_20220707_1939'), ('Reporting', '0004_reportedmission_day_pk'), ('Reporting', '0005_auto_20220718_1112'), ('Reporting', '0006_alter_reportedmission_options_and_more'), ('Reporting', '0007_alter_reportedmission_day'), ('Reporting', '0008_alter_epascode_ts_code_alter_presencedata_ts_code'), ('Reporting', '0009_alter_bankholiday_options_alter_epascode_options_and_more'), ('Reporting', '0010_alter_bankholiday_options_alter_epascode_options_and_more')]

    initial = True

    dependencies = [
        ('Projects', '0010_project_depreciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='EpasCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('ts_code', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReportedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hours', models.FloatField()),
            ],
            options={
                'ordering': ['period', 'year', 'month', 'researcher'],
            },
        ),
        migrations.CreateModel(
            name='ReportedWorkWorkpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpackages', to='Reporting.reportedwork')),
                ('workpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to='Projects.workpackage')),
            ],
            options={
                'ordering': ['report', 'workpackage'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_hours', to='Reporting.reportedwork')),
                ('report_wp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ts_hours', to='Reporting.reportedworkworkpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_start', models.DateField(db_index=True)),
                ('rp_end', models.DateField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='Projects.project')),
            ],
            options={
                'ordering': ['project', 'rp_start'],
            },
        ),
        migrations.AddField(
            model_name='reportedwork',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to='Reporting.reportingperiod'),
        ),
        migrations.AddField(
            model_name='reportedwork',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to='Projects.researcher'),
        ),
        migrations.CreateModel(
            name='ReportedMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_missions', to='Reporting.reportingperiod')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_missions', to='Projects.researcher')),
            ],
            options={
                'ordering': ['period', 'researcher', 'day'],
            },
        ),
        migrations.CreateModel(
            name='PresenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('hours', models.FloatField()),
                ('ts_code', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Reporting.epascode')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Projects.researcher')),
            ],
            options={
                'ordering': ['researcher', 'day'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('cost', models.FloatField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='Projects.researcher')),
            ],
            options={
                'ordering': ['year', 'researcher'],
            },
        ),
        migrations.AddConstraint(
            model_name='epascode',
            constraint=models.UniqueConstraint(fields=('code',), name='reporting_epascode_unique'),
        ),
        migrations.AddConstraint(
            model_name='bankholiday',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'day'), name='reporting_bankholiday_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheethours',
            constraint=models.UniqueConstraint(fields=('report', 'report_wp', 'day'), name='reporting_timesheethours_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('project', 'rp_start'), name='reporting_reportingperiod_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportedworkworkpackage',
            constraint=models.UniqueConstraint(fields=('report', 'workpackage'), name='reporting_reportedworkworkpackage_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportedwork',
            constraint=models.UniqueConstraint(fields=('period', 'researcher', 'year', 'month'), name='reporting_reportedwork_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportedmission',
            constraint=models.UniqueConstraint(fields=('period', 'researcher', 'day'), name='reporting_reportedmission_unique'),
        ),
        migrations.AddConstraint(
            model_name='presencedata',
            constraint=models.UniqueConstraint(fields=('researcher', 'day'), name='reporting_presencedata_unique'),
        ),
        migrations.AddConstraint(
            model_name='personnelcost',
            constraint=models.UniqueConstraint(fields=('year', 'researcher'), name='reporting_personnelcost_unique'),
        ),
        migrations.AddField(
            model_name='reportedmission',
            name='workpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_missions', to='Projects.workpackage'),
        ),
        #migrations.RunPython(
        #    code=Reporting.migrations.0003_auto_20220707_1939.migrate_data_from_old_reporting,
        #),
        migrations.AddField(
            model_name='reportedmission',
            name='day_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_mission', to='Reporting.presencedata'),
        ),
        #migrations.RunPython(
        #    code=Reporting.migrations.0005_auto_20220718_1112.migrate_missions,
        #),
        migrations.AlterModelOptions(
            name='reportedmission',
            options={'ordering': ['period', 'day__researcher', 'day__day']},
        ),
        migrations.RemoveConstraint(
            model_name='reportedmission',
            name='reporting_reportedmission_unique',
        ),
        migrations.RemoveField(
            model_name='reportedmission',
            name='day',
        ),
        migrations.RemoveField(
            model_name='reportedmission',
            name='researcher',
        ),
        migrations.RenameField(
            model_name='reportedmission',
            old_name='day_pk',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='reportedmission',
            name='workpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_missions', to='Projects.workpackage'),
        ),
        migrations.AddConstraint(
            model_name='reportedmission',
            constraint=models.UniqueConstraint(fields=('period', 'day'), name='reporting_reportedmission_unique'),
        ),
        migrations.AlterField(
            model_name='reportedmission',
            name='day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='reported_missions', to='Reporting.presencedata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epascode',
            name='ts_code',
            field=models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='presencedata',
            name='ts_code',
            field=models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness')], default='', max_length=2),
        ),
        migrations.AlterModelOptions(
            name='reportedworkworkpackage',
            options={'default_permissions': (), 'ordering': ['report', 'workpackage']},
        ),
        migrations.AlterModelOptions(
            name='bankholiday',
            options={'default_permissions': (), 'ordering': ['year', 'month', 'day'], 'permissions': [('holiday_view', 'View list of bank holidays'), ('holiday_manage', 'Manage list of bank holidays')]},
        ),
        migrations.AlterModelOptions(
            name='epascode',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': [('epas_view', 'View list of EPAS codes'), ('epas_manage', 'Manage list of EPAS codes')]},
        ),
        migrations.AlterModelOptions(
            name='personnelcost',
            options={'default_permissions': (), 'ordering': ['year', 'researcher'], 'permissions': [('costs_view', 'View personnel costs'), ('costs_manage', 'Manage personnel costs')]},
        ),
        migrations.AlterModelOptions(
            name='presencedata',
            options={'default_permissions': (), 'ordering': ['researcher', 'day'], 'permissions': [('presences_view', 'View presences'), ('presences_view_own', 'View own presences'), ('presences_manage', 'Manage presences'), ('presences_manage_own', 'Manage own presences')]},
        ),
        migrations.AlterModelOptions(
            name='reportedmission',
            options={'default_permissions': (), 'ordering': ['period', 'day__researcher', 'day__day'], 'permissions': [('rp_mission_view', 'View reported missions'), ('rp_mission_view_own', 'View own reported missions'), ('rp_mission_manage', 'Manage reported missions'), ('rp_mission_manage_own', 'Manage own reported missions')]},
        ),
        migrations.AlterModelOptions(
            name='reportedwork',
            options={'default_permissions': (), 'ordering': ['period', 'year', 'month', 'researcher'], 'permissions': [('rp_work_view', 'View reported work'), ('rp_work_view_own', 'View own reported work'), ('rp_work_manage', 'Manage reported work'), ('rp_work_manage_own', 'Manage own reported work')]},
        ),
        migrations.AlterModelOptions(
            name='reportingperiod',
            options={'default_permissions': (), 'ordering': ['project', 'rp_start'], 'permissions': [('reporting_view', 'View reporting periods'), ('reporting_manage', 'Manage reporting periods'), ('reporting_manage_own', 'Manage reporting periods of own projects')]},
        ),
        migrations.AlterModelOptions(
            name='timesheethours',
            options={'default_permissions': (), 'permissions': [('timesheet_view', 'View timesheets'), ('timesheet_view_own', 'View own timesheets'), ('timesheet_manage', 'Manage timesheets'), ('timesheet_manage_own', 'Manage own timesheets')]},
        ),
    ]
