# Generated by Django 4.0.4 on 2022-07-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0010_project_depreciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='EpasCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('ts_code', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReportedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hours', models.FloatField()),
            ],
            options={
                'ordering': ['period', 'year', 'month', 'researcher'],
            },
        ),
        migrations.CreateModel(
            name='ReportedWorkWorkpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpackages', to='Reporting.reportedwork')),
                ('workpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to='Projects.workpackage')),
            ],
            options={
                'ordering': ['report', 'workpackage'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_hours', to='Reporting.reportedwork')),
                ('report_wp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ts_hours', to='Reporting.reportedworkworkpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_start', models.DateField(db_index=True)),
                ('rp_end', models.DateField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='Projects.project')),
            ],
            options={
                'ordering': ['project', 'rp_start'],
            },
        ),
        migrations.AddField(
            model_name='reportedwork',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to='Reporting.reportingperiod'),
        ),
        migrations.AddField(
            model_name='reportedwork',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to='Projects.researcher'),
        ),
        migrations.CreateModel(
            name='ReportedMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_missions', to='Reporting.reportingperiod')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_missions', to='Projects.researcher')),
            ],
            options={
                'ordering': ['period', 'researcher', 'day'],
            },
        ),
        migrations.CreateModel(
            name='PresenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('hours', models.FloatField()),
                ('ts_code', models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness'), ('OA', 'Other absences')], default='', max_length=2)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Reporting.epascode')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Projects.researcher')),
            ],
            options={
                'ordering': ['researcher', 'day'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('cost', models.FloatField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='Projects.researcher')),
            ],
            options={
                'ordering': ['year', 'researcher'],
            },
        ),
        migrations.AddConstraint(
            model_name='epascode',
            constraint=models.UniqueConstraint(fields=('code',), name='reporting_epascode_unique'),
        ),
        migrations.AddConstraint(
            model_name='bankholiday',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'day'), name='reporting_bankholiday_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheethours',
            constraint=models.UniqueConstraint(fields=('report', 'report_wp', 'day'), name='reporting_timesheethours_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('project', 'rp_start'), name='reporting_reportingperiod_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportedworkworkpackage',
            constraint=models.UniqueConstraint(fields=('report', 'workpackage'), name='reporting_reportedworkworkpackage_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportedwork',
            constraint=models.UniqueConstraint(fields=('period', 'researcher', 'year', 'month'), name='reporting_reportedwork_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportedmission',
            constraint=models.UniqueConstraint(fields=('period', 'researcher', 'day'), name='reporting_reportedmission_unique'),
        ),
        migrations.AddConstraint(
            model_name='presencedata',
            constraint=models.UniqueConstraint(fields=('researcher', 'day'), name='reporting_presencedata_unique'),
        ),
        migrations.AddConstraint(
            model_name='personnelcost',
            constraint=models.UniqueConstraint(fields=('year', 'researcher'), name='reporting_personnelcost_unique'),
        ),
    ]
