# Generated by Django 4.0.4 on 2022-07-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_project_depreciation'),
        ('Reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedmission',
            name='workpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_missions', to='Projects.workpackage'),
        ),
    ]
