# Generated by Django 4.0.4 on 2022-07-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0003_auto_20220707_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedmission',
            name='day_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_mission', to='Reporting.presencedata'),
        ),
    ]
