# Generated by Django 4.0.4 on 2022-07-18 09:12

from django.db import migrations
from Reporting.models import PresenceData, ReportedMission


def migrate_missions(apps, schema_editor):
    for m in ReportedMission.objects.all():
        print("Updating mission day {0!s} for {1!s}".format(m.day, m.researcher))
        m.day_pk = PresenceData.objects.get(researcher=m.researcher, day=m.day)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0004_reportedmission_day_pk'),
    ]

    operations = [
        migrations.RunPython(migrate_missions),
    ]
