# Generated by Django 4.0.4 on 2022-07-26 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0006_alter_reportedmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedmission',
            name='day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='reported_missions', to='Reporting.presencedata'),
            preserve_default=False,
        ),
    ]
