# Generated by Django 4.0.4 on 2022-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0007_alter_reportedmission_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epascode',
            name='ts_code',
            field=models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='presencedata',
            name='ts_code',
            field=models.CharField(choices=[('', 'None'), ('HO', 'Holidays'), ('MI', 'Mission'), ('IL', 'Illness')], default='', max_length=2),
        ),
    ]
