# Generated by Django 4.0.4 on 2022-08-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0009_alter_bankholiday_options_alter_epascode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankholiday',
            options={'default_permissions': (), 'ordering': ['year', 'month', 'day'], 'permissions': [('holiday_view', 'View list of bank holidays'), ('holiday_manage', 'Manage list of bank holidays')]},
        ),
        migrations.AlterModelOptions(
            name='epascode',
            options={'default_permissions': (), 'ordering': ['code'], 'permissions': [('epas_view', 'View list of EPAS codes'), ('epas_manage', 'Manage list of EPAS codes')]},
        ),
        migrations.AlterModelOptions(
            name='personnelcost',
            options={'default_permissions': (), 'ordering': ['year', 'researcher'], 'permissions': [('costs_view', 'View personnel costs'), ('costs_manage', 'Manage personnel costs')]},
        ),
        migrations.AlterModelOptions(
            name='presencedata',
            options={'default_permissions': (), 'ordering': ['researcher', 'day'], 'permissions': [('presences_view', 'View presences'), ('presences_view_own', 'View own presences'), ('presences_manage', 'Manage presences'), ('presences_manage_own', 'Manage own presences')]},
        ),
        migrations.AlterModelOptions(
            name='reportedmission',
            options={'default_permissions': (), 'ordering': ['period', 'day__researcher', 'day__day'], 'permissions': [('rp_mission_view', 'View reported missions'), ('rp_mission_view_own', 'View own reported missions'), ('rp_mission_manage', 'Manage reported missions'), ('rp_mission_manage_own', 'Manage own reported missions')]},
        ),
        migrations.AlterModelOptions(
            name='reportedwork',
            options={'default_permissions': (), 'ordering': ['period', 'year', 'month', 'researcher'], 'permissions': [('rp_work_view', 'View reported work'), ('rp_work_view_own', 'View own reported work'), ('rp_work_manage', 'Manage reported work'), ('rp_work_manage_own', 'Manage own reported work')]},
        ),
        migrations.AlterModelOptions(
            name='reportingperiod',
            options={'default_permissions': (), 'ordering': ['project', 'rp_start'], 'permissions': [('reporting_view', 'View reporting periods'), ('reporting_manage', 'Manage reporting periods'), ('reporting_manage_own', 'Manage reporting periods of own projects')]},
        ),
        migrations.AlterModelOptions(
            name='timesheethours',
            options={'default_permissions': (), 'permissions': [('timesheet_view', 'View timesheets'), ('timesheet_view_own', 'View own timesheets'), ('timesheet_manage', 'Manage timesheets'), ('timesheet_manage_own', 'Manage own timesheets')]},
        ),
    ]
