# Generated by Django 4.0.4 on 2022-09-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uuid', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('V', 'Verified'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=1)),
            ],
            options={
                'ordering': ['surname', 'name'],
                'permissions': [('registration_manage', 'Manage registration requests')],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='accountmanagement_registrationrequest_unique'),
        ),
    ]
