# Generated by Django 4.0.4 on 2022-09-02 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='submit_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 1, 1, 0)),
            preserve_default=False,
        ),
    ]
