# Generated by Django 4.0.4 on 2022-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0002_registrationrequest_submit_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='ldap_hash',
            field=models.CharField(default='', max_length=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='samba_hash',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
