# Generated by Django 3.2.5 on 2022-04-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0009_auto_20220422_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True)),
                ('desciption', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
    ]
