# Generated by Django 4.2.20 on 2025-04-14 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('Accounting', '0001_initial'), ('Accounting', '0002_rename_desciption_gae_description'), ('Accounting', '0003_auto_20220428_1238'), ('Accounting', '0004_auto_20220428_1240'), ('Accounting', '0005_auto_20220428_1707'), ('Accounting', '0006_auto_20220428_1745'), ('Accounting', '0007_auto_20220428_1832'), ('Accounting', '0008_auto_20220428_1838'), ('Accounting', '0009_auto_20220429_1700'), ('Accounting', '0010_auto_20220429_1729'), ('Accounting', '0011_auto_20220502_1247'), ('Accounting', '0012_auto_20220502_1651'), ('Accounting', '0013_splitcontab_vocespesa_depreciation_splitvariazione_and_more'), ('Accounting', '0014_splitcontab_notes'), ('Accounting', '0015_auto_20220628_1506'), ('Accounting', '0016_alter_variazione_data'), ('Accounting', '0017_alter_mandato_data'), ('Accounting', '0018_remove_splitimpegno_accounting_splitimpegno_unique_and_more'), ('Accounting', '0019_splitcontab_include_funding'), ('Accounting', '0020_gae_include_funding'), ('Accounting', '0021_alter_gae_options_alter_impegno_options_and_more'), ('Accounting', '0022_alter_gae_options_alter_vocespesa_options'), ('Accounting', '0023_alter_splitcontab_options_alter_vocespesa_options')]

    initial = True

    dependencies = [
        ('Projects', '0009_auto_20220422_1837'),
        ('Projects', '0010_project_depreciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoceSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voce', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['voce'],
            },
        ),
        migrations.CreateModel(
            name='Impegno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esercizio', models.IntegerField()),
                ('esercizio_orig', models.IntegerField()),
                ('pg_impegno', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('im_competenza', models.FloatField(default=0.0)),
                ('im_residui', models.FloatField(default=0.0)),
                ('doc_competenza', models.FloatField(default=0.0)),
                ('doc_residui', models.FloatField(default=0.0)),
                ('pagato_competenza', models.FloatField(default=0.0)),
                ('pagato_residui', models.FloatField(default=0.0)),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['gae', 'esercizio_orig', 'pg_impegno'],
            },
        ),
        migrations.CreateModel(
            name='Variazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esercizio', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('stato', models.CharField(max_length=3)),
                ('riferimenti', models.TextField()),
                ('descrizione', models.TextField()),
                ('cdrSrc', models.CharField(max_length=30)),
                ('cdrDst', models.CharField(max_length=30)),
                ('importo', models.FloatField(default=0.0)),
                ('data', models.DateField()),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['gae', 'data'],
            },
        ),
        migrations.CreateModel(
            name='Stanziamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esercizio', models.IntegerField()),
                ('stanziamento', models.FloatField(default=0.0)),
                ('assestato', models.FloatField(default=0.0)),
                ('impegnato', models.FloatField(default=0.0)),
                ('residuo', models.FloatField(default=0.0)),
                ('pagato', models.FloatField(default=0.0)),
                ('da_pagare', models.FloatField(default=0.0)),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
                ('var_meno', models.FloatField(default=0.0)),
                ('var_piu', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['gae', 'esercizio', 'voce'],
            },
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_mandato', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=300)),
                ('id_terzo', models.IntegerField()),
                ('terzo', models.CharField(max_length=200)),
                ('importo', models.FloatField()),
                ('data', models.DateField()),
                ('impegno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.impegno')),
            ],
            options={
                'ordering': ['impegno', 'data'],
            },
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('gae', 'pg_impegno'), name='accounting_impegno_unique'),
        ),
        migrations.AddConstraint(
            model_name='stanziamento',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'voce'), name='accounting_stanziamento_unique'),
        ),
        migrations.AddConstraint(
            model_name='variazione',
            constraint=models.UniqueConstraint(fields=('gae', 'numero'), name='accounting_variazione_unique'),
        ),
        migrations.AlterModelOptions(
            name='impegno',
            options={'ordering': ['gae', 'esercizio', 'pg_impegno']},
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AlterField(
            model_name='impegno',
            name='pg_impegno',
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'pg_impegno'), name='accounting_impegno_unique'),
        ),
        migrations.AlterModelOptions(
            name='impegno',
            options={'ordering': ['gae', 'esercizio', 'numero']},
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.RemoveConstraint(
            model_name='variazione',
            name='accounting_variazione_unique',
        ),
        migrations.RenameField(
            model_name='impegno',
            old_name='pg_impegno',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='mandato',
            old_name='pg_mandato',
            new_name='numero',
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'numero'), name='accounting_impegno_unique'),
        ),
        migrations.AddConstraint(
            model_name='variazione',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'numero'), name='accounting_variazione_unique'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='mandato',
            constraint=models.UniqueConstraint(fields=('impegno', 'numero'), name='accounting_mandato_unique'),
        ),
        migrations.AlterModelOptions(
            name='impegno',
            options={'ordering': ['gae', 'esercizio_orig', 'numero']},
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('esercizio', 'numero'), name='accounting_impegno_unique'),
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('esercizio_orig', 'numero', 'esercizio'), name='accounting_impegno_unique'),
        ),
        migrations.RemoveConstraint(
            model_name='variazione',
            name='accounting_variazione_unique',
        ),
        migrations.AddConstraint(
            model_name='variazione',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'numero', 'voce'), name='accounting_variazione_unique'),
        ),
        migrations.RemoveConstraint(
            model_name='variazione',
            name='accounting_variazione_unique',
        ),
        migrations.AddConstraint(
            model_name='variazione',
            constraint=models.UniqueConstraint(fields=('gae', 'data', 'numero', 'voce'), name='accounting_variazione_unique'),
        ),
        migrations.CreateModel(
            name='SplitContab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.researcher')),
            ],
            options={
                'ordering': ['gae', 'responsible'],
            },
        ),
        migrations.AddField(
            model_name='vocespesa',
            name='depreciation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SplitVariazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.FloatField()),
                ('dst_contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_dst', to='Accounting.splitcontab')),
                ('dst_voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='var_dst', to='Accounting.vocespesa')),
                ('src_contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_src', to='Accounting.splitcontab')),
                ('src_voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='var_src', to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['src_contab', 'dst_contab'],
            },
        ),
        migrations.CreateModel(
            name='SplitImpegno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.splitcontab')),
                ('impegno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.impegno')),
            ],
            options={
                'ordering': ['contab', 'impegno'],
            },
        ),
        migrations.CreateModel(
            name='SplitBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('importo', models.FloatField()),
                ('contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.splitcontab')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['contab', 'voce', 'year'],
            },
        ),
        migrations.AddConstraint(
            model_name='splitimpegno',
            constraint=models.UniqueConstraint(fields=('contab', 'impegno'), name='accounting_splitimpegno_unique'),
        ),
        migrations.AddConstraint(
            model_name='splitcontab',
            constraint=models.UniqueConstraint(fields=('gae', 'responsible'), name='accounting_splitcontab_unique'),
        ),
        migrations.AddConstraint(
            model_name='splitbudget',
            constraint=models.UniqueConstraint(fields=('contab', 'voce', 'year'), name='accounting_splitbudget_unique'),
        ),
        migrations.AddField(
            model_name='splitcontab',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio_orig', 'esercizio', 'numero'), name='accounting_impegno_unique'),
        ),
        migrations.AlterField(
            model_name='variazione',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data',
            field=models.DateField(default=datetime.date(2022, 6, 29)),
            preserve_default=False,
        ),
        migrations.RemoveConstraint(
            model_name='splitimpegno',
            name='accounting_splitimpegno_unique',
        ),
        migrations.AddConstraint(
            model_name='splitimpegno',
            constraint=models.UniqueConstraint(fields=('impegno',), name='accounting_splitimpegno_unique'),
        ),
        migrations.AddField(
            model_name='splitcontab',
            name='include_funding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gae',
            name='include_funding',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='impegno',
            options={'default_permissions': (), 'ordering': ['gae', 'esercizio_orig', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='mandato',
            options={'default_permissions': (), 'ordering': ['impegno', 'data']},
        ),
        migrations.AlterModelOptions(
            name='splitbudget',
            options={'default_permissions': (), 'ordering': ['contab', 'voce', 'year']},
        ),
        migrations.AlterModelOptions(
            name='splitimpegno',
            options={'default_permissions': (), 'ordering': ['contab', 'impegno']},
        ),
        migrations.AlterModelOptions(
            name='splitvariazione',
            options={'default_permissions': (), 'ordering': ['src_contab', 'dst_contab']},
        ),
        migrations.AlterModelOptions(
            name='stanziamento',
            options={'default_permissions': (), 'ordering': ['gae', 'esercizio', 'voce']},
        ),
        migrations.AlterModelOptions(
            name='variazione',
            options={'default_permissions': (), 'ordering': ['gae', 'data']},
        ),
        migrations.AlterModelOptions(
            name='gae',
            options={'default_permissions': (), 'ordering': ['project', 'name'], 'permissions': [('gae_view', 'View GAE list'), ('gae_view_own', 'View GAE of own projects'), ('gae_manage', 'Manage GAE list')]},
        ),
        migrations.AlterModelOptions(
            name='splitcontab',
            options={'default_permissions': (), 'ordering': ['gae', 'responsible'], 'permissions': [('splitcontab_view', 'View split accounting'), ('splitcontab_view_own', 'View own split accounting'), ('splitcontab_manage', 'Manage split accounting'), ('splitcontab_manage_own', 'Manage own split accounting')]},
        ),
        migrations.AlterModelOptions(
            name='vocespesa',
            options={'default_permissions': (), 'ordering': ['voce']},
        ),
    ]
