# Generated by Django 3.2.5 on 2022-04-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gae',
            old_name='desciption',
            new_name='description',
        ),
    ]
