# Generated by Django 3.2.5 on 2022-04-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_rename_desciption_gae_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impegno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esercizio', models.IntegerField()),
                ('esercizio_orig', models.IntegerField()),
                ('pg_impegno', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('im_competenza', models.FloatField(default=0.0)),
                ('im_residui', models.FloatField(default=0.0)),
                ('doc_competenza', models.FloatField(default=0.0)),
                ('doc_residui', models.FloatField(default=0.0)),
                ('pagato_competenza', models.FloatField(default=0.0)),
                ('pagato_residui', models.FloatField(default=0.0)),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
            ],
            options={
                'ordering': ['gae', 'esercizio_orig', 'pg_impegno'],
            },
        ),
        migrations.CreateModel(
            name='VoceSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voce', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['voce'],
            },
        ),
        migrations.CreateModel(
            name='Variazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esercizio', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('stato', models.CharField(max_length=3)),
                ('riferimenti', models.TextField()),
                ('descrizione', models.TextField()),
                ('cdrSrc', models.CharField(max_length=30)),
                ('cdrDst', models.CharField(max_length=30)),
                ('importo', models.FloatField(default=0.0)),
                ('data', models.DateField()),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['gae', 'data'],
            },
        ),
        migrations.CreateModel(
            name='Stanziamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esercizio', models.IntegerField()),
                ('stanziamento', models.FloatField(default=0.0)),
                ('assestato', models.FloatField(default=0.0)),
                ('impegnato', models.FloatField(default=0.0)),
                ('residuo', models.FloatField(default=0.0)),
                ('pagato', models.FloatField(default=0.0)),
                ('da_pagare', models.FloatField(default=0.0)),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['gae', 'esercizio', 'voce'],
            },
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_mandato', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('id_terzo', models.IntegerField()),
                ('terzo', models.CharField(max_length=200)),
                ('importo', models.FloatField()),
                ('data', models.DateField()),
                ('impegno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.impegno')),
            ],
            options={
                'ordering': ['impegno', 'data'],
            },
        ),
        migrations.AddField(
            model_name='impegno',
            name='voce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa'),
        ),
    ]
