# Generated by Django 3.2.5 on 2022-04-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20220428_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stanziamenti',
            new_name='Stanziamento',
        ),
        migrations.RenameModel(
            old_name='Variazioni',
            new_name='Variazione',
        ),
    ]
