# Generated by Django 3.2.5 on 2022-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0006_auto_20220428_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impegno',
            options={'ordering': ['gae', 'esercizio', 'numero']},
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.RemoveConstraint(
            model_name='variazione',
            name='accounting_variazione_unique',
        ),
        migrations.RenameField(
            model_name='impegno',
            old_name='pg_impegno',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='mandato',
            old_name='pg_mandato',
            new_name='numero',
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'numero'), name='accounting_impegno_unique'),
        ),
        migrations.AddConstraint(
            model_name='variazione',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'numero'), name='accounting_variazione_unique'),
        ),
    ]
