# Generated by Django 3.2.5 on 2022-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_auto_20220428_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='mandato',
            constraint=models.UniqueConstraint(fields=('impegno', 'numero'), name='accounting_mandato_unique'),
        ),
    ]
