# Generated by Django 3.2.5 on 2022-04-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_auto_20220428_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impegno',
            options={'ordering': ['gae', 'esercizio_orig', 'numero']},
        ),
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('esercizio', 'numero'), name='accounting_impegno_unique'),
        ),
    ]
