# Generated by Django 3.2.5 on 2022-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_auto_20220429_1700'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('esercizio_orig', 'numero', 'esercizio'), name='accounting_impegno_unique'),
        ),
    ]
