# Generated by Django 3.2.5 on 2022-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0010_auto_20220429_1729'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variazione',
            name='accounting_variazione_unique',
        ),
        migrations.AddConstraint(
            model_name='variazione',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio', 'numero', 'voce'), name='accounting_variazione_unique'),
        ),
    ]
