# Generated by Django 4.0.4 on 2022-06-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_project_depreciation'),
        ('Accounting', '0012_auto_20220502_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitContab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.gae')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.researcher')),
            ],
            options={
                'ordering': ['gae', 'responsible'],
            },
        ),
        migrations.AddField(
            model_name='vocespesa',
            name='depreciation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SplitVariazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.FloatField()),
                ('dst_contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_dst', to='Accounting.splitcontab')),
                ('dst_voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='var_dst', to='Accounting.vocespesa')),
                ('src_contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_src', to='Accounting.splitcontab')),
                ('src_voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='var_src', to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['src_contab', 'dst_contab'],
            },
        ),
        migrations.CreateModel(
            name='SplitImpegno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.splitcontab')),
                ('impegno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.impegno')),
            ],
            options={
                'ordering': ['contab', 'impegno'],
            },
        ),
        migrations.CreateModel(
            name='SplitBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('importo', models.FloatField()),
                ('contab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.splitcontab')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounting.vocespesa')),
            ],
            options={
                'ordering': ['contab', 'voce', 'year'],
            },
        ),
        migrations.AddConstraint(
            model_name='splitimpegno',
            constraint=models.UniqueConstraint(fields=('contab', 'impegno'), name='accounting_splitimpegno_unique'),
        ),
        migrations.AddConstraint(
            model_name='splitcontab',
            constraint=models.UniqueConstraint(fields=('gae', 'responsible'), name='accounting_splitcontab_unique'),
        ),
        migrations.AddConstraint(
            model_name='splitbudget',
            constraint=models.UniqueConstraint(fields=('contab', 'voce', 'year'), name='accounting_splitbudget_unique'),
        ),
    ]
