# Generated by Django 4.0.4 on 2022-06-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0013_splitcontab_vocespesa_depreciation_splitvariazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitcontab',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
