# Generated by Django 3.2.5 on 2022-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0014_splitcontab_notes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='impegno',
            name='accounting_impegno_unique',
        ),
        migrations.AddConstraint(
            model_name='impegno',
            constraint=models.UniqueConstraint(fields=('gae', 'esercizio_orig', 'esercizio', 'numero'), name='accounting_impegno_unique'),
        ),
    ]
