# Generated by Django 3.2.5 on 2022-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0015_auto_20220628_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variazione',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
