# Generated by Django 4.0.4 on 2022-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0017_alter_mandato_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='splitimpegno',
            name='accounting_splitimpegno_unique',
        ),
        migrations.AddConstraint(
            model_name='splitimpegno',
            constraint=models.UniqueConstraint(fields=('impegno',), name='accounting_splitimpegno_unique'),
        ),
    ]
