# Generated by Django 4.0.4 on 2022-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0018_remove_splitimpegno_accounting_splitimpegno_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitcontab',
            name='include_funding',
            field=models.BooleanField(default=False),
        ),
    ]
