# Generated by Django 4.0.4 on 2022-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0019_splitcontab_include_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='gae',
            name='include_funding',
            field=models.BooleanField(default=True),
        ),
    ]
