# Generated by Django 4.0.4 on 2022-08-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0020_gae_include_funding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gae',
            options={'default_permissions': (), 'ordering': ['project', 'name'], 'permissions': [('view', 'View GAE list'), ('view_own', 'View GAE of own projects'), ('manage', 'Manage GAE list')]},
        ),
        migrations.AlterModelOptions(
            name='impegno',
            options={'default_permissions': (), 'ordering': ['gae', 'esercizio_orig', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='mandato',
            options={'default_permissions': (), 'ordering': ['impegno', 'data']},
        ),
        migrations.AlterModelOptions(
            name='splitbudget',
            options={'default_permissions': (), 'ordering': ['contab', 'voce', 'year']},
        ),
        migrations.AlterModelOptions(
            name='splitcontab',
            options={'default_permissions': (), 'ordering': ['gae', 'responsible']},
        ),
        migrations.AlterModelOptions(
            name='splitimpegno',
            options={'default_permissions': (), 'ordering': ['contab', 'impegno']},
        ),
        migrations.AlterModelOptions(
            name='splitvariazione',
            options={'default_permissions': (), 'ordering': ['src_contab', 'dst_contab']},
        ),
        migrations.AlterModelOptions(
            name='stanziamento',
            options={'default_permissions': (), 'ordering': ['gae', 'esercizio', 'voce']},
        ),
        migrations.AlterModelOptions(
            name='variazione',
            options={'default_permissions': (), 'ordering': ['gae', 'data']},
        ),
        migrations.AlterModelOptions(
            name='vocespesa',
            options={'default_permissions': (), 'ordering': ['voce'], 'permissions': [('view', 'View list of expense chapters'), ('manage', 'Manage list of expense chapters')]},
        ),
    ]
