# Generated by Django 4.0.4 on 2022-08-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0021_alter_gae_options_alter_impegno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gae',
            options={'default_permissions': (), 'ordering': ['project', 'name'], 'permissions': [('gae_view', 'View GAE list'), ('gae_view_own', 'View GAE of own projects'), ('gae_manage', 'Manage GAE list')]},
        ),
        migrations.AlterModelOptions(
            name='vocespesa',
            options={'default_permissions': (), 'ordering': ['voce'], 'permissions': [('voce_view', 'View list of expense chapters'), ('voce_manage', 'Manage list of expense chapters')]},
        ),
    ]
